### ISSUE TITLE
Level System Überarbeiten

### ISSUE THREAD

**Issue by pyrox25** [A3ReallifeRPG/ReallifeRPG5.0#250]

**Comment by vabene1111** [comment]
Erfahrungssystem muss dringend überarbeitet werden ( ca 1000 mal sammeln um von lvl 2 auf 3 zu kommen ) !! Bin nach gut 7 stunden lvl 3 das allerdings auch nur dank eines Achievements das man im normal modus nicht so schnell bekommt
