### ISSUE TITLE
Air Service NPC funktioniert nicht

### ISSUE THREAD

**Issue by Greenywastaken** [A3ReallifeRPG/ReallifeRPG5.0#252]
Heli reparatur am Airfield
Funktionell ? Wenn ja benutzbar machen für Adac

**Comment by vabene1111** [comment]
air_sp marker fehlt, greeny lern mal bugs zu reporten

**Comment by Greenywastaken** [comment]
Bene, lern man auf Datenschutz zu achten

**Comment by vabene1111** [comment]
air_sp marker fehlt
