### ISSUE TITLE
Nachricht falls ingame

### ISSUE THREAD

**Issue by Aventur591** [A3ReallifeRPG/ReallifeRPG5.0#359]
Im Webpannel wird nicht angezeigt das es probleme gibt wenn man ingame ist, falls man die täglichen xp abholt.

**Comment by Aventur591** [comment]
Immer noch keine Meldung gut geschriebene exp die an der website angezeigt wird wird nach reconneten "gelöscht"

**Comment by Greenywastaken** [comment]
anbindung an hauptserver bitte auf den Hauptserver gehen und dann testen, danke :)
