### ISSUE TITLE
Strandgut überdenken (preis-exp)

### ISSUE THREAD

**Issue by Aventur591** [A3ReallifeRPG/ReallifeRPG5.0#401]
Eine Tour mit Sprinter 20-30 min 1k exp und 60-100k geld
Strandgut 200k 400 xp 10-20 min.... und das sicher da kein markt

**Comment by vabene1111** [comment]
geht aber nur 1 mal die stunde und nur für eine person auf dem server

**Comment by vabene1111** [comment]
bzw habe jetzt den timer etwas hoch gestellt
