### ISSUE TITLE
tankstellen meldung geht nicht

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#490]

**Comment by Aventur591** [comment]
http://images.akamai.steamusercontent.com/ugc/450736355957223636/C07C9A577378EE513BC1E3B49F956DE49C969702/

**Comment by Aventur591** [comment]
und marker abundzu nicht auf der karte

**Comment by br1zey** [comment]
marker kommt auch nicht immer
