### ISSUE TITLE
ADAC task Icon

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#512]
Wenn man nach einem Restart auf den Server kommt und es kommt der erste Auftrag herrein, dann bekommt man eine Message Box mit folgendem Fehler: "Picture \ui_f\data\map\mapcontrol\taskicon_ca.paa not fround".
Ich denke es hängt mit dem kleinen Bildchen, welches man bei dem kleinen Hinweiß in der Mitte, welcher immer bei einem neuen Auftrag bekommt, zusammen.

**Comment by br1zey** [comment]
this is magic Arma !

**Comment by br1zey** [comment]
bitte testen
