### ISSUE TITLE
skillpunkt level 1 ?

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#534]
leute sagen das dadurch das man mit lvl 1 startet man den ersten punkt nicht bekommt

**Comment by br1zey** [comment]
mhhh die starten mit lvl 1 und 1 Skill Point !

**Comment by br1zey** [comment]
10 mal neu getestet bekomme 1 skill punkt ich denke die meinen den der durchs geschenk fehlt ....
