### ISSUE TITLE
Fahrzeuge nach Restart nicht mehr in DB drin

### ISSUE THREAD

**Issue by Trefferquote0** [A3ReallifeRPG/ReallifeRPG5.0#564]
Gelegentlich fehlen Autos in der DB nach nem Restart. In meinem Fall ein Stealth KFZ, welches im HQ stand. LG Daniel Locke
James Green hat schon viele KFZ verloren. Bis auf eins standen auch alle im HQ zum Restart.

**Comment by br1zey** [comment]
einfach mal impoundet ?

**Comment by Trefferquote0** [comment]
Natürlich nicht

**Comment by br1zey** [comment]
Is in deine Gerage ?
