### ISSUE TITLE
Cop-Items aus Z-Inventar dürfen nicht entfernt werden

### ISSUE THREAD

**Issue by Trefferquote0** [A3ReallifeRPG/ReallifeRPG5.0#565]
Cop-Items aus Z-Inventar dürfen nicht entfernt werden, da Cops in der Nähe sind... :D :D 
Lediglich durchsuchen durch Kollegen hilft einigermaßen, man landet aber auf der Wanted List

**Comment by br1zey** [comment]
dan pack die doch ins auto und parck sie ein
