### ISSUE TITLE
Vorschlag! Abgleich Wanted List - Kennzeichenabfrage

### ISSUE THREAD

**Issue by Trefferquote0** [A3ReallifeRPG/ReallifeRPG5.0#566]
Wenn der Name des Besitzers aus der DB gelesen wird, könnte man vielleicht auch gleich mit der Wanted List abgleichen und den Namen dann rot einfärben in der Kennzeichenabfrage.

**Comment by vabene1111** [comment]
da er nicht aus der DB gelesen wir wollen wir dafür keine extra abfrage machen (performance).

einfach nach der abfrage kurz ins z menü. Generell sollten kennzeichen abfragen eher seltener benutzt werden.
