### ISSUE TITLE
Script error blaulicht + evt. spyglass

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#569]
https://forum.realliferpg.de/wpbt/index.php?issue/64-diverse-skripterrors

suchen in welchen fahrzeug (verutlich eins der DAR?!?)

**Comment by br1zey** [comment]
Jo is in der Datei wie auf dem bild zu sehn es fehlt ein _light und es muss _lights sein xD fusch am bau

**Comment by RS4Memphis** [comment]
DAR Fehler ist behoben muss nur noch hochgelsaden werden... Was ist mit den Rest?
