### ISSUE TITLE
Kill log kaputt

### ISSUE THREAD

**Issue by Trefferquote0** [A3ReallifeRPG/ReallifeRPG5.0#617]
https://service.realliferpg.de/#kills
Wurde gestern nachweislich getötet, Medic Nein gedrückt und respawned: kein Mord oder Anzeige durch wen gestorben im Panel ersichtlich

**Comment by Greenywastaken** [comment]
Kills werden im Moment nicht geloggt, nur verdurstet und verhungern da ace es uns sehr schwer macht

**Comment by vabene1111** [comment]
ist einfach kaputt, ersetzt durch unconscious log
