### ISSUE TITLE
BAF --> CUP

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#629]
BAF_Offroad_D >>>>> CUP_C_LR_Transport_CTK
LandRover_TK_CIV_EP1 >>>>> CUP_B_LR_Transport_CZ_D
BAF_Offroad_W >>>>> CUP_O_LR_Transport_TKA
LandRover_CZ_EP1 >>>>> CUP_B_LR_Transport_GB_W

UPDATE vehicles SET classname='CUP_C_LR_Transport_CTK' WHERE classname='BAF_Offroad_D'

**Comment by br1zey** [comment]
UPDATE vehicles SET classname='CUP_C_LR_Transport_CTK' WHERE classname='BAF_Offroad_D'
UPDATE vehicles SET classname='CUP_B_LR_Transport_CZ_D' WHERE classname='LandRover_TK_CIV_EP1'
UPDATE vehicles SET classname='CUP_O_LR_Transport_TKA' WHERE classname='BAF_Offroad_W'
UPDATE vehicles SET classname='CUP_B_LR_Transport_GB_W' WHERE classname='LandRover_CZ_EP1'

**Comment by br1zey** [comment]
UPDATE vehicles SET classname='CUP_C_LR_Transport_CTK' WHERE classname='BAF_Offroad_D';
UPDATE vehicles SET classname='CUP_B_LR_Transport_CZ_D' WHERE classname='LandRover_TK_CIV_EP1';
UPDATE vehicles SET classname='CUP_O_LR_Transport_TKA' WHERE classname='BAF_Offroad_W';
UPDATE vehicles SET classname='CUP_B_LR_Transport_GB_W' WHERE classname='LandRover_CZ_EP1';

**Comment by br1zey** [comment]
UPDATE vehicles SET classname='CUP_C_LR_Transport_CTK' WHERE classname='LandRover_ACR'
