### ISSUE TITLE
Zum testen Deaktiviert

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#722]
Taxi raus
cop Blaulicht shift l raus
wreck removal runter

**Comment by br1zey** [comment]
TAXI Init

[this, this] call ace_common_fnc_claim;this enableSimulation false; this allowDamage false;  this addAction ["Dienst Antreten", {life_isOnDutyTaxi = true;[[player],"TON_fnc_goOnDuty",false,false] spawn life_fnc_mp;}];  this addAction ["Dienst beenden", {life_isOnDutyTaxi = false;[[player],"TON_fnc_goOffDuty",false,false] spawn life_fnc_mp;}];this addAction[format["%1 ($%2)",localize (getText(missionConfigFile >> "Licenses" >> "taxi" >> "displayName")), [(getNumber(missionConfigFile >> "Licenses" >> "taxi" >> "price"))] call life_fnc_numberText],life_fnc_buyLicense,"taxi",0,false,false,"",' !license_civ_taxi && playerSide == civilian '];

**Comment by vabene1111** [comment]
bell heli
status bar player count (was ich nicht glaube aber was solls)
