### ISSUE TITLE
alle icons mit no.paa bzw ohne icon

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#748]
- weizen

**Comment by vabene1111** [comment]
Aktuelle Liste:

Car Alarm
Schlafsack/Matte

Meische
Weizen

Snickers (ingame Smikers, einfach schokoriegel)
Cola

Crafting Item Kabine (vermutich teil größerer LKW's)

Barriere

**Comment by IamCerberus** [comment]
https://drive.google.com/drive/folders/0B2Y8HX3VXSK6OXY2QUtLYzhEQ3c
Im Ordner Icons
