### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#809]
ich habe 2bugs im support gesagt die lieber nicht auf die website sollten wegen fixen und so sonnst kann sich jeder magazine für waffen und westen glitchen, wen man sich westen kauft und kein geld hat und sie direkt nach dem kauf obwohl man sie nicht bezahlt hat auf den boden legt kann man die sich kostenlos hollen und wen man in den westen magas hat und im kleiderladen ist und wieder rausgeht und die magazine umlagert dann lädt der inventar neu und man hat sie in der weste und im rucksack oder in der normalen kleidung immer noch heißt man kann duplizieren

**Comment by br1zey** [comment]
I inventar IM Kleidungsladen nicht aufrufbar
