### ISSUE TITLE
ACE Micro DAGR rein machen

### ISSUE THREAD

**Issue by vabene1111** [A3ReallifeRPG/ReallifeRPG5.0#877]
https://forum.realliferpg.de/index.php?thread/1006-ace-dagr-einf%C3%BChrung/&postID=5741#post5762

**Comment by IamCerberus** [comment]
Compass and headings
Date and hour synced to the mission
Elevation (above or below sea level)
Current speed
GPS with topographic and satellite view
Creating, naming, deleting waypoints
Friendly identification (BLUFOR tracker need to be on)
The MicroDAGR is also able to connect to your vector to retrieve data from it

Würde nein sagen.

**Comment by IamCerberus** [comment]
http://ace3mod.com/wiki/feature/microdagr.html
