### ISSUE TITLE
Schlüsselbund

### ISSUE THREAD

**Issue by br1zey** [A3ReallifeRPG/ReallifeRPG5.0#93]
Keine schlüssel !!!!!!

http://images.akamai.steamusercontent.com/ugc/454110978787757951/2B2925352E5610C7644FB09E34B41C68B05841B6/

**Comment by vabene1111** [comment]
sollte behoben sein

**Comment by Greenywastaken** [comment]
wer hat bitte seine menüfarbe auf lila ???????
