### ISSUE TITLE
Autos, Flugzeuge, SAG westen

### ISSUE THREAD

**Issue by BlueIce0504** [A3ReallifeRPG/ReallifeRPG5.0#954]
Die neuen Autos und die Neuen Flugzeuge Sind nicht beim Händler zu Finden Sowie die SAG westen beim Donater shop

**Comment by br1zey** [comment]
Was für Autos ?????
Ja Westen und Flugzeuge kommen noch

**Comment by BlueIce0504** [comment]
Es sollten Doch neue Autos kommen

Am 29.09.2016 15:33 schrieb "br1zey" <notifications@github.com>:
