### ISSUE TITLE
Infopanel ADAC ränge

### ISSUE THREAD

**Issue by emt1803** [A3ReallifeRPG/ReallifeRPG5.0#962]
# Bugs:
1. **Ausweiße**: Durch die neuen Ränge, zeigt es sobald man wenn den Ausweiß zeigt: "Error" an.

2. **Infopanel**: Hier wird durch die neuen Ränge ebenso Error angezeigt

# Wünsche:
1. **Neue Kopfbedeckungen:** 
Kopfhörer(Standard Arma 3 Kopfhörer mit Headset): Für RP technische Zwecke usw. zB. für Leitstelle usw.
Gasmaske: Ebenso für RP technische Zwecke, zB. bei Verkehrsunfällen wo Benzin austritt usw.

2. **Neues Fahrzeug:** Tanklaster (Standardskin): Wäre sehr praktisch, da sehr sehr viele unserer Aufträge mit Auftanken zu tun haben. Ebenso wäre es förderlich für das RP. Ebenso gut da wir Helikopter mit den normalen Kanistern nicht auftanken können, da diese zu wenig bringen.

Ich bedanke mich schon mal im Vorraus,

Hans Peter

**Comment by br1zey** [comment]
Bug 1 Behoben

**Comment by vabene1111** [comment]
Kopfhörer sind drin, gas gibst nicht, tanker ist auch drin muss jedoch normal an der Raffinerie gefüllt werden

**Comment by vabene1111** [comment]
Es bleibt noch für @Kaibu 
Infopanel: Hier wird durch die neuen Ränge ebenso Error angezeigt

**Comment by vabene1111** [comment]
1. Praktikant
2.  Azubi
3. Automobil Assistent
4. Geselle
5. Mechaniker
6. Service Mechaniker
7. Mechatroniker
8. Service Mechatroniker
9. Techniker
10. Service Techniker
11. Meister
12. Ingenieur
13. COO
14. CEO
