### ISSUE TITLE
Cop Vorschläge.

### ISSUE THREAD

**Issue by IamCerberus** [A3ReallifeRPG/ReallifeRPG5.0#973]
Geschwindigkeitsmesser auf Entfernungsmesser legen.
Botsspawn beim Medic HQ für die Cops und in Madmans Bay (besser für neues HQ)
P99 Teaser wechseln auf eine andere Waffe. (Cops können die Waffe langsam nicht mehr sehen) Vorschlag: CZ 75 Duty.
Fahrzeuge mit Lightbar aber mit schwarzem Skin.

**Comment by br1zey** [comment]
- [x] Geschwindigkeitsmesser auf Entfernungsmesser legen.
- [ ] Botsspawn beim Medic HQ für die Cops und in Madmans Bay (besser für neues HQ)
- [ ] P99 Teaser wechseln auf eine andere Waffe. (Cops können die Waffe langsam nicht mehr sehen) Vorschlag: CZ 75 Duty.
- [ ] Fahrzeuge mit Lightbar aber mit schwarzem Skin.
